### PR TITLE
Fix a crash in canvas when "Block third-party cookies" is enabled in Chrome

### LINKED ISSUE #347: Different domain in iframe does not work with "Block third-party cookies" enabled in Chrome
To reproduce:

 - Go to chrome://settings/cookies
 - Set "Block third-party cookies" radio-button to selected
 - Open designer at prod (https://alpha.webstudio.is/designer/{projectID})
 - The canvas is unable to connect to the designer (for example, clicking on canvas doesn't make an item selected)
 
Need to find a way to make it work with the setting enabled. If that's impossible, implement some UI that tells the user to disable the setting.

---

https://bugs.chromium.org/p/chromium/issues/detail?id=357625
https://github.com/remix-run/remix/issues/3659

### PR DESCRIPTION
**Pull request by rpominov**
Fixes #347

## Before requesting a review

- [ ] if the PR is WIP - use draft mode
- [x] made a self-review
- [x] added inline comments where things may be not obvious (the "why", not "what")
- [ ] what kind of review is needed?
  - [x] conceptual
  - [ ] detailed
  - [ ] with testing

## Test cases

- [ ] step by step interaction description and what is expected to happen

## Before merging

- [ ] tested locally and on preview environment (preview dev login: 5de6)
- [ ] updated [test cases](https://github.com/webstudio-is/webstudio-designer/blob/main/apps/designer/docs/test-cases.md) document
- [ ] added tests
- [ ] if any new env variables are added, added them to `.env.example` and the `designer/env-check.js` if mandatory

### CODE REVIEW

**Comment by rpominov** [comment]
Build fails due to https://github.com/webstudio-is/webstudio-designer/pull/298#issuecomment-1288769465

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx [hunk 1]
```diff
@@ -0,0 +1,35 @@
+// This is a temporary work around for https://github.com/remix-run/remix/issues/3659
```
Comment (kof) [inline packages/react-sdk/src/tree/session-storage-polyfill.tsx:1]: uhh, this looks fishy: consumers will think sessionStorage works, but it basically just shifts the problem to warnings instead of error. Shouldn't consumers be testing if sessionStorage is available before using it?

Comment (kof) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:1]: what is currently using sessionStorage?

Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:1]: Remix uses it to restore scroll position. They need to fix it on their side. Hopefully they'll do it as the issue is already open, then we can remove this workaround.

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+// The code is based on this discussion https://bugs.chromium.org/p/chromium/issues/detail?id=357625
+const polyfill = `(function () {
```
Comment (kof) [inline packages/react-sdk/src/tree/session-storage-polyfill.tsx:4]: its such a weird way to do the polyfill ... and then render it specifically before scrollrestoration over react ...
can't it just be imported as a normal script, before anything else runs?

Comment (kof) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:4]: we will have the same issue if we try access sessionStorage in some script if it runs before this

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+  try {
+    const key = "__session_storage_availability_test__";
+    sessionStorage.setItem(key, "test");
+    sessionStorage.removeItem(key);
```
Comment (kof) [inline packages/react-sdk/src/tree/session-storage-polyfill.tsx:8]: I am confused by the test and the implementation of this, is setItem forbidden or removeItem?
If both why do we need both for the test?
If both why do we not warn in all polyfilled methods?

Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:8]: The test is the first line `setItem`. The second line is just a cleanup.

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx (hunk 2 above)
Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:4]: > render it specifically before scrollrestoration

The fact that it goes before `<ScrollRestoration>` is accidental, I just needed to put it before all scripts.

> can't it just be imported as a normal script

Not sure putting it in something like `entry.client.tsx` will work, as it'll probably go after `<ScrollRestoration>` in that case, but I can try.

File: apps/designer/app/canvas/canvas.tsx [hunk 4]
```diff
@@ -65,6 +65,7 @@ const useElementsTree = () => {
     if (rootInstance === undefined) return;
 
     return createElementsTree({
+      embeded: true,
```
Comment (kof) [inline apps/designer/app/canvas/canvas.tsx:68]: typo, but also maybe there is a better name, e.g. "sandbox"
```suggestion
      embedded: true,
```

Comment (rpominov) [reply apps/designer/app/canvas/canvas.tsx]: Renamed to sandbox

Comment (kof) [reply apps/designer/app/canvas/canvas.tsx]: if using "embed", correct word would be probably "embed" as a noun

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+        setItem: (key: string, val: unknown) => {
+          // eslint-disable-next-line no-console
+          console.warn(
+            `Session storage is unavailable due to Error "${
+              (error as Error).message
+            }". A polyfill is used to set value of "${key}". The value will be lost when the page is reloaded.`
+          );
+          data.set(key, String(val));
+        },
+        getItem: (key: string) => {
```
Comment (kof) [inline packages/react-sdk/src/tree/session-storage-polyfill.tsx:25]: so getItem won't throw?

**Review by kof — APPROVED** [review]

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+        },
+        clear: () => {
+          data.clear();
+        },
+      },
+    });
+  }
+}.toString();
+
+export const SessionStoragePolyfill = () => (
```
[the remark this answers is not in the document]
Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:39]: No, because there's no code that tries to use LocalStorage without checking for availability.
The polyfill is a workaround for the bug in Remix where it uses SessionStorage without checking that it's available.

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx (hunk 5 above)
Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:25]: Yes, it won't. Not sure I understood the question :)

Comment (kof) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:25]: its weird that setItem throws an error but getItem doesn't ... so reading from sessionStorage is allowed?

Comment (kof) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:25]: I am talking about native sessionStorage api, because you are warning only in setItem as if the getItem isn't the same problem

File: packages/react-sdk/src/tree/session-storage-polyfill.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (kof) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:39]: I am talking about potential future 3rd party code

[the remark this answers is not in the document]
Comment (rpominov) [reply packages/react-sdk/src/tree/session-storage-polyfill.tsx:39]: I think we should assume that other code will not have bugs like Remix. This polyfill is not an ideal solution, I don't think it's a good idea to add one for LocalStorage just in case.
